name: Michael-Walker.com
favicon: null
layout_spectrum: 0.9201105448883027
typography_spectrum: 0.7210544340778142
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5bca6'
    - '#58533d'
    - '#80884c'
    - '#426fbe'
    - '#c72824'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
